using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using MiniController.Models;
using MiniController.Helpers;

namespace MiniController.Generators;

public static class SourceCodeGenerator
{
    public static void GenerateEndpointRegistration(SourceProductionContext context, EndpointGroupClass endpointGroup)
    {
        ValidateEndpoints(context, endpointGroup);

        var methodCount = endpointGroup.EndpointMethods.Count;
        var estimatedCapacity =
            500 +
            (methodCount * 200) +
            (endpointGroup.RoutePrefix?.Length ?? 0) * methodCount +
            100;

        var source = new StringBuilder(estimatedCapacity);

        source.AppendLine("// <auto-generated>");
        source.AppendLine("// 由EndpointGenerator自动生成，请勿修改");
        source.AppendLine("// </auto-generated>");
        source.AppendLine();
        source.AppendLine("using Microsoft.AspNetCore.Builder;");
        source.AppendLine("using Microsoft.AspNetCore.Http;");
        source.AppendLine();
        source.AppendLine($"namespace {endpointGroup.Namespace}");
        source.AppendLine("{");
        source.AppendLine($"    public static class {endpointGroup.ClassName}Extensions");
        source.AppendLine("    {");
        source.AppendLine($"        public static IEndpointRouteBuilder Map{endpointGroup.ClassName}(this IEndpointRouteBuilder builder)");
        source.AppendLine("        {");

        // 检查控制器路由是否包含 [action] 占位符
        var hasActionPlaceholder = !string.IsNullOrEmpty(endpointGroup.RoutePrefix) && 
                                  endpointGroup.RoutePrefix.Contains("[action]");

        if (hasActionPlaceholder)
        {
            // 对于包含 [action] 的路由，直接注册每个方法到 builder，不使用 MapGroup
            GenerateDirectMethodRegistrations(source, endpointGroup);
        }
        else
        {
            // 对于不包含 [action] 的路由，使用传统的 MapGroup 方式
            GenerateGroupMethodRegistrations(source, endpointGroup);
        }

        source.AppendLine();
        source.AppendLine("            return builder;");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");

        context.AddSource($"{endpointGroup.ClassName}Extensions.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    /// <summary>
    /// 生成直接方法注册（用于包含 [action] 的路由）
    /// </summary>
    private static void GenerateDirectMethodRegistrations(StringBuilder source, EndpointGroupClass endpointGroup)
    {
        foreach (var method in endpointGroup.EndpointMethods)
        {
            // 解析控制器路由中的 [action] 占位符
            var resolvedRoute = RouteTemplateResolver.ResolveActionTemplate(
                endpointGroup.RoutePrefix!, 
                method.Name, 
                method.HttpMethod);

            // 如果方法有额外的路由模板，则追加
            if (!string.IsNullOrEmpty(method.RouteTemplate))
            {
                if (resolvedRoute.EndsWith("/") || method.RouteTemplate.StartsWith("/"))
                {
                    resolvedRoute = resolvedRoute.TrimEnd('/') + "/" + method.RouteTemplate.TrimStart('/');
                }
                else
                {
                    resolvedRoute = resolvedRoute + "/" + method.RouteTemplate;
                }
            }

            source.Append($"            builder.Map{method.HttpMethod}(\"{resolvedRoute}\", {endpointGroup.ClassName}.{method.Name})");

            // 添加授权
            if (method.Authorize != null)
            {
                var authorizeCall = BuildAuthorizeCall(method.Authorize);
                if (!string.IsNullOrEmpty(authorizeCall))
                {
                    source.Append(authorizeCall);
                }
            }
            else if (endpointGroup.Authorize != null)
            {
                var authorizeCall = BuildAuthorizeCall(endpointGroup.Authorize);
                if (!string.IsNullOrEmpty(authorizeCall))
                {
                    source.Append(authorizeCall);
                }
            }

            // 添加API Explorer设置
            if (method.ApiExplorerSettings != null)
            {
                var apiExplorerCall = BuildApiExplorerSettingsCall(method.ApiExplorerSettings);
                if (!string.IsNullOrEmpty(apiExplorerCall))
                {
                    source.Append(apiExplorerCall);
                }
            }
            else
            {
                source.Append(".WithOpenApi()");
            }

            // 添加响应类型
            foreach (var responseType in method.ResponseTypes ?? Enumerable.Empty<ResponseTypeMetadata>())
            {
                AppendProducesCall(source, responseType);
            }

            // 添加过滤器
            if (!string.IsNullOrEmpty(method.FilterType))
            {
                source.Append($".AddEndpointFilter<{method.FilterType}>()");
            }
            else if (!string.IsNullOrEmpty(endpointGroup.FilterType))
            {
                source.Append($".AddEndpointFilter<{endpointGroup.FilterType}>()");
            }

            source.AppendLine(";");
        }
    }

    /// <summary>
    /// 生成组方法注册（用于不包含 [action] 的路由）
    /// </summary>
    private static void GenerateGroupMethodRegistrations(StringBuilder source, EndpointGroupClass endpointGroup)
    {
        source.AppendLine($"            var group = builder.MapGroup(\"{endpointGroup.RoutePrefix}\");");

        if (!string.IsNullOrEmpty(endpointGroup.Name))
        {
            source.AppendLine($"            group.WithName(\"{endpointGroup.Name}\");");
        }

        if (endpointGroup.Authorize != null)
        {
            var authorizeCall = BuildAuthorizeCall(endpointGroup.Authorize);
            source.AppendLine($"            group{authorizeCall};");
        }

        if (!string.IsNullOrEmpty(endpointGroup.FilterType))
        {
            source.AppendLine($"            group.AddEndpointFilter<{endpointGroup.FilterType}>();");
        }

        source.AppendLine();

        foreach (var method in endpointGroup.EndpointMethods)
        {
            BuildMethodRegistration(source, method, endpointGroup.ClassName);
        }
    }

    public static void GenerateMiniControllerRegistration(SourceProductionContext context, List<(string nameSpace, string className)> ClassInfoList)
    {
        var estimatedCapacity = 300 + (ClassInfoList.Count * 50);
        var Extension = new StringBuilder(estimatedCapacity);

        Extension.AppendLine("// <auto-generated>");
        Extension.AppendLine("// 由EndpointGenerator自动生成，请勿修改");
        Extension.AppendLine("// </auto-generated>");
        Extension.AppendLine();
        Extension.AppendLine("using Microsoft.AspNetCore.Builder;");
        Extension.AppendLine("using Microsoft.AspNetCore.Http;");

        var uniqueNamespaces = ClassInfoList.Select(c => c.nameSpace).Distinct();
        foreach (var ns in uniqueNamespaces)
        {
            Extension.AppendLine($"using {ns};");
        }

        Extension.AppendLine();
        Extension.AppendLine("namespace Microsoft.AspNetCore.Builder");
        Extension.AppendLine("{");
        Extension.AppendLine("    public static class MiniControllerExtensions");
        Extension.AppendLine("    {");
        Extension.AppendLine("        public static IEndpointRouteBuilder MapMiniController(this IEndpointRouteBuilder builder)");
        Extension.AppendLine("        {");

        foreach (var classInfo in ClassInfoList)
        {
            Extension.AppendLine($"            builder.Map{classInfo.className}();");
        }

        Extension.AppendLine("            return builder;");
        Extension.AppendLine("        }");
        Extension.AppendLine("    }");
        Extension.AppendLine("}");

        context.AddSource("MiniControllerExtensions.g.cs", SourceText.From(Extension.ToString(), Encoding.UTF8));
    }

    private static void BuildMethodRegistration(StringBuilder source, EndpointMethod method, string className)
    {
        if (method == null || string.IsNullOrEmpty(method.Name))
        {
            return; // 跳过无效的方法
        }

        source.Append($"            group.Map{method.HttpMethod}(\"{method.RouteTemplate}\", {className}.{method.Name})");

        if (method.Authorize != null)
        {
            var authorizeCall = BuildAuthorizeCall(method.Authorize);
            if (!string.IsNullOrEmpty(authorizeCall))
            {
                source.Append(authorizeCall);
            }
        }

        if (method.ApiExplorerSettings != null)
        {
            var apiExplorerCall = BuildApiExplorerSettingsCall(method.ApiExplorerSettings);
            if (!string.IsNullOrEmpty(apiExplorerCall))
            {
                source.Append(apiExplorerCall);
            }
        }
        else
        {
            source.Append(".WithOpenApi()");
        }

        // 添加响应类型
        foreach (var responseType in method.ResponseTypes ?? Enumerable.Empty<ResponseTypeMetadata>())
        {
            AppendProducesCall(source, responseType);
        }

        // 添加过滤器
        if (!string.IsNullOrEmpty(method.FilterType))
        {
            source.Append($".AddEndpointFilter<{method.FilterType}>()");
        }

        source.AppendLine(";");
    }

    private static void AppendProducesCall(StringBuilder source, ResponseTypeMetadata responseType)
    {
        if (responseType == null) return;

        if (!string.IsNullOrEmpty(responseType.TypeName))
        {
            source.Append($".Produces<{responseType.TypeName}>({responseType.StatusCode}");
            if (!string.IsNullOrEmpty(responseType.ContentType))
            {
                source.Append($", \"{responseType.ContentType}\"");
            }
            source.Append(')');
        }
        else
        {
            source.Append($".Produces({responseType.StatusCode}");
            if (!string.IsNullOrEmpty(responseType.ContentType))
            {
                source.Append($", \"{responseType.ContentType}\"");
            }
            source.Append(')');
        }
    }

    private static string BuildAuthorizeCall(AuthorizeMetadata metadata)
    {
        if (metadata?.AllowAnonymous == true)
        {
            return ".AllowAnonymous()";
        }

        if (metadata == null)
            return string.Empty;

        var arguments = new List<string>(3);

        if (!string.IsNullOrEmpty(metadata.Policy))
            arguments.Add($"\"{metadata.Policy}\"");

        if (!string.IsNullOrEmpty(metadata.Roles))
            arguments.Add($"Roles: \"{metadata.Roles}\"");

        if (!string.IsNullOrEmpty(metadata.AuthenticationSchemes))
            arguments.Add($"AuthenticationSchemes: \"{metadata.AuthenticationSchemes}\"");

        if (arguments.Count == 0)
            return ".RequireAuthorization()";

        return $".RequireAuthorization({string.Join(", ", arguments)})";
    }

    private static string BuildApiExplorerSettingsCall(ApiExplorerSettingsMetadata settings)
    {
        if (settings == null) return string.Empty;

        var result = new StringBuilder(64);

        if (settings.IgnoreApi == true)
        {
            result.Append(".ExcludeFromDescription()");
        }
        else
        {
            result.Append(".WithOpenApi()");
        }

        if (!string.IsNullOrEmpty(settings.GroupName))
        {
            result.Append($".WithTags(\"{settings.GroupName}\")");
        }

        return result.ToString();
    }

    private static void ValidateEndpoints(SourceProductionContext context, EndpointGroupClass endpointGroup)
    {
        if (endpointGroup?.EndpointMethods == null)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                CreateDiagnosticDescriptor("MC002", "无效的端点组", "端点组或其方法列表为空", DiagnosticSeverity.Error),
                Location.None));
            return;
        }

        var routeMap = new Dictionary<string, List<string>>(endpointGroup.EndpointMethods.Count);

        foreach (var method in endpointGroup.EndpointMethods)
        {
            if (method == null) continue;

            var key = $"{method.HttpMethod}:{method.RouteTemplate}";
            if (!routeMap.TryGetValue(key, out var methods))
            {
                routeMap[key] = new List<string> { method.Name };
            }
            else
            {
                methods.Add(method.Name);
                context.ReportDiagnostic(Diagnostic.Create(
                    CreateDiagnosticDescriptor("MC001", "路由冲突",
                        $"控制器 {endpointGroup.ClassName} 中的方法 {string.Join(", ", methods)} 具有相同的路由 {key}",
                        DiagnosticSeverity.Warning),
                    Location.None));
            }
        }
    }

    private static DiagnosticDescriptor CreateDiagnosticDescriptor(string id, string title, string messageFormat, DiagnosticSeverity severity)
    {
        return new DiagnosticDescriptor(
            id,
            title,
            messageFormat,
            "MiniController",
            severity,
            isEnabledByDefault: true,
            description: $"MiniController 源码生成器诊断：{title}"
        );
    }
}